#!/usr/bin/env python3
"""Every reachable decision of `surfaceplate adopt`, run against a real installed repository and
judged - the matrix `DR-58` defines, produced by `ACT-057`.

    .venv/bin/python tests/test_adopt_matrix.py            # run the matrix; fails if the report is stale
    .venv/bin/python tests/test_adopt_matrix.py --write    # run it and rewrite audit/validation/ADOPT_MATRIX.md
    .venv/bin/python tests/test_adopt_matrix.py --only T2- # a prefix of case ids, while working on the suite

The library is `tests/adopt_matrix.py`; the screen-driving half is `tests/adopt_matrix_screens.py`
and needs `textual`. The report this writes is tracked, carries no dates and no temporary paths, and
is compared byte for byte on every run: a run that changes the matrix - a gate added, a case
removed, a check count moved - fails until the report is regenerated and read.

A case passing means its checks passed. The record's outcome (`governance/assurance/`) is the
maintainer's to set; this suite states what it measured.
"""

from __future__ import annotations

import platform
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

import adopt_matrix as M  # noqa: E402

REPORT = ROOT / "audit" / "validation" / "ADOPT_MATRIX.md"


def _choices(case: M.Case) -> str:
    parts = []
    if case.route == "interactive":
        if M.free_gates(case.level, case.ui):
            parts.append(f"statuses {case.status_pattern}")
        parts.append(f"artefacts {case.artefact_class}")
        if case.above_floor != "none":
            parts.append(f"above floor: {case.above_floor}")
        if case.variant:
            parts.append(case.variant)
    else:
        parts.append(case.route + (f" ({case.stage})" if case.stage else "") + (f" {case.variant}" if case.variant else ""))
        if case.route == "screens":
            parts.append(f"statuses {case.status_pattern}")
    return "; ".join(parts)


def _expected(case: M.Case) -> str:
    if case.expect_codes:
        return "findings " + ", ".join(case.expect_codes)
    if case.expect_refusal:
        return f"refused at the review: “{case.expect_refusal}”"
    if case.route in ("cancel", "refusal", "propose-no-level"):
        return "refused or cancelled, nothing written"
    return "PASS, no findings"


def render_report(cases: list[M.Case], outcomes: list[M.Outcome], gaps_found: list[str]) -> str:
    by_id = {o.case.id: o for o in outcomes}
    total_checks = sum(len(o.checks) for o in outcomes)
    failed = [o for o in outcomes if o.failed]
    tiers = {}
    for c in cases:
        tiers.setdefault(c.tier, []).append(c)
    py = ".".join(platform.python_version_tuple()[:2])
    try:
        import textual

        tx = textual.__version__
    except Exception:  # noqa: BLE001
        tx = "not installed"
    lines = [
        "# `adopt` — the combinatorial validation matrix",
        "",
        "Generated by `tests/test_adopt_matrix.py --write` (`ACT-057`); the same script fails in CI when",
        "this file and the matrix it runs disagree. Do not edit by hand. What it records is what the suite",
        "measured on its last run; the maintainer's conclusion is `governance/assurance/AE-0001-adopt-matrix.yaml`.",
        "",
        "## What was validated, and how (`DR-58`)",
        "",
        "**FACT.** Every case below runs `surfaceplate adopt` against a real git repository with the",
        "standard installed, through the same `wizard.run` the terminal uses (`ScriptedInterview` answers",
        "the same `plan` the screens render), then judges four things: the written profile (round-trips,",
        "validates against the installed schema, and carries per field exactly the value and origin the",
        "case entitles it to); the provenance sidecar (an origin for every leaf, the six kinds only, the",
        "bulk decision's count); the files on disk (git sees exactly the profile, the sidecar and the",
        "seeds chosen, no draft); and the real checker (`check_conformance.evaluate`) after committing,",
        "which must report `PASS` with no findings, or exactly the finding codes the case expects.",
        "",
        "Expectations are derived from the case's choices and from the run's own proposals, never from",
        "a second profile builder. Free text is one distinct sentinel per field per run, so every typed",
        "value is attributable and nothing invented can pass. Cross-gate status interactions are argued",
        "independent (`sections.build_gate` reads one gate's answers alone) and not swept: 3^11 status",
        "combinations at `standard` are named and not run.",
        "",
        "## The repository shapes",
        "",
        "| shape | what it holds | what discovery therefore does |",
        "|---|---|---|",
        f"| `bare` | `{M.BARE_SOURCE}` and `{M.BARE_SCANNER}` | no language, no lock file, no workflow, no artefact matching any gate: every seed free, the decisions form asks for the language, the lock file and the scanner file; the decision record is scaffolded |",
        "| `rich` | a Python source, a lock file, a CI workflow with named steps, a scanner workflow, a keyword-matching document for every gate, a findings register, three fitting record directories, a decisions folder, and one plain document matching nothing | every artefact and reference proposed as discovered; the decision record id asked |",
        "| `mixed` | a Python source, a pinned-dependency file no lock-file rule names, one workflow with tests and the scanner, an archived register, a placeholder-bearing decision log, a YAML directory fitting no control, a changelog, and the plain document | the lock file asked; the archived and rejected documents offered and never proposed; the seed row leads those fields; the unfit directory offered and never proposed |",
        "",
        "## Coverage, by tier",
        "",
        "| tier | dimension | cases |",
        "|---|---|---|",
        "| T2 | every level × interface answer × shape; every free gate in every status, cycled, in bulk, and in a bulk with two statuses explicit | " + str(len(tiers.get("T2", []))) + " |",
        "| T3 | every artefact field with the seed row and a typed path (found is T2's default) | " + str(len(tiers.get("T3", []))) + " |",
        "| T4 | every above-floor control ticked singly and all together, per level, on rich and bare | " + str(len(tiers.get("T4", []))) + " |",
        "| T5 | the decisions form's variants and the design review's stress cases, expected-finding cases included | " + str(len(tiers.get("T5", []))) + " |",
        "| T6 | routes: propose then replay, resume after every stage, edit per leaf class, cancel at every point, every refusal class | " + str(len(tiers.get("T6", []))) + " |",
        "| T7 | the screens driven headlessly through a full run at every configuration, compared with the scripted run | " + str(len(tiers.get("T7", []))) + " |",
        "",
        f"**{len(cases)} cases, {total_checks} checks.** Coverage self-check: {'no gaps' if not gaps_found else '; '.join(gaps_found)}.",
        "",
        "## Environment",
        "",
        f"Python {py}, Textual {tx}, Linux; one machine, one interpreter. The date of the run is in the",
        "assurance record, not here.",
        "",
        "## Evidence gaps (stated, not discovered)",
        "",
        "- No real terminal: the screens are driven headlessly by Textual's pilot at 80×24.",
        "- One Python and one Textual version, on Linux.",
        "- Free text is one equivalence class per field (a sentinel); length, Unicode and multi-line prose are covered by `tests/test_adopt.py`, not here.",
        "- Cross-gate status interactions are argued independent from the code, not swept.",
        "- The history audit (SP034, SP035) is exercised only against a fresh fixture history: one back-dated commit, then the adoption.",
        "- The `advanced` register's text is not proof-read by the suite; one case asserts it changes nothing written.",
        "- The checker's own correctness is assumed: it is the oracle for the final verdict.",
        "- A typed record directory for a pattern-C control is exercised only as the present-but-unfit directory (`SP056`); the fitting directory is exercised as discovered.",
        "",
        "## The cases",
        "",
        "| case | level | interface | shape | choices | expected | checks | origins recorded |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for case in sorted(cases, key=lambda c: c.id):
        o = by_id.get(case.id)
        checks = f"{len(o.checks)}" if o else "not run"
        origins = ", ".join(f"{k} {v}" for k, v in sorted(o.origins.items())) if o and o.origins else "—"
        lines.append(f"| `{case.id}` | {case.level} | {'yes' if case.ui else 'no'} | {case.shape} | {_choices(case)} | {_expected(case)} | {checks} | {origins} |")
    lines += [
        "",
        "## Reproduce",
        "",
        "```",
        ".venv/bin/python tests/test_adopt_matrix.py",
        "```",
        "",
        "Every case builds its repository from the shape table above under a temporary directory, so the",
        "run is self-contained; the fixtures are committed with yesterday's date so a seed created in the",
        "same second as the adoption commit never reads as crossing a gate before its artefact.",
        "",
    ]
    if failed:
        lines.append(f"**{len(failed)} case(s) failed on the last run that wrote this file; this file must not be committed in that state.**")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    argv = sys.argv[1:]
    write = "--write" in argv
    only = next((argv[i + 1] for i, a in enumerate(argv) if a == "--only" and i + 1 < len(argv)), "")
    cases = M.enumerate_cases()
    print(f"the matrix: {len(cases)} cases enumerated from the catalogue")
    gaps = M.coverage_gaps(cases)
    if gaps:
        print("COVERAGE GAPS (the enumeration does not reach):")
        for gap in gaps:
            print(f"  - {gap}")
    selected = [c for c in cases if c.id.startswith(only)] if only else cases
    outcomes: list[M.Outcome] = []
    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="surfaceplate-matrix-") as tmp:
        tmp_path = Path(tmp)
        built = {shape: M.build_shape(tmp_path / "shapes", shape) for shape in M.SHAPES}
        for shape in M.SHAPES:
            found = M.discover.scan(built[shape])
            print(f"  shape {shape}: {len(found.artefacts)} artefacts, {len(found.lock_files)} lock, {len(found.ci_steps)} steps, "
                  f"{len(found.scanner_workflows)} scanner workflow(s), {len(found.free_seeds)}+{len(found.free_control_seeds)} seeds free, "
                  f"language {'detected' if M.detect.detect_languages(built[shape]) else 'not detected'}")
        for index, case in enumerate(selected, start=1):
            outcome = M.run_case(case, built, tmp_path / "cases")
            outcomes.append(outcome)
            failed = outcome.failed
            mark = "FAIL" if failed else "PASS"
            extra = f"  {outcome.verdict} {list(outcome.codes)}" if outcome.codes else ""
            print(f"  {mark}  {case.id:<8} {case.config:<16} {case.shape:<5} {_choices(case)[:60]:<60} {len(outcome.checks):>3} checks {outcome.seconds:5.2f}s{extra}")
            for name, _ok, detail in failed:
                print(f"        - {name}: {detail}")
            # A case's working copy is removed once judged: two hundred repositories add up.
            for path in (tmp_path / "cases").glob(f"{case.id}*"):
                M.shutil.rmtree(path, ignore_errors=True)
            if case.variant == "nonslug":
                M.shutil.rmtree(tmp_path / "cases" / "___", ignore_errors=True)
    elapsed = time.perf_counter() - started
    checks = sum(len(o.checks) for o in outcomes)
    failures = [(o.case.id, name, detail) for o in outcomes for name, ok, detail in o.checks if not ok]
    print()
    print(f"  ran {len(outcomes)} case(s), {checks} checks, in {elapsed:.0f}s")
    if gaps:
        failures.append(("coverage", "the enumeration reaches every dimension", "; ".join(gaps)))
    if not only:
        report = render_report(cases, outcomes, gaps)
        if write:
            REPORT.parent.mkdir(parents=True, exist_ok=True)
            REPORT.write_text(report, encoding="utf-8")
            print(f"  wrote {REPORT.relative_to(ROOT)}")
        else:
            current = REPORT.read_text(encoding="utf-8") if REPORT.is_file() else ""
            if current != report:
                failures.append(("report", f"{REPORT.relative_to(ROOT)} is current", "the tracked report differs from this run's; regenerate with --write and read the diff"))
    if failures:
        print(f"ADOPT_MATRIX=FAIL  ({len(failures)} failed, {checks - len(failures)} passed; {len(outcomes)} runs)")
        for case_id, name, detail in failures[:60]:
            print(f"  - {case_id}: {name}: {detail[:300]}")
        return 1
    print(f"ADOPT_MATRIX=PASS  ({checks} checks; {len(outcomes)} runs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
